# Generated by Django 5.2.17 on 2026-10-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0003_alter_entreprise_adresse_and_more'),
        ('ExpeditionApp', '0001_initial'),
        ('vehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.IntegerField()),
                ('sstatut', models.CharField(choices=[('p', 'Proposee'), ('a', 'Acceptee'), ('r', 'Refusee'), ('c', 'Annulee')], max_length=50)),
                ('date_proposition', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ExpeditionApp.expedition')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='EntrepriseApp.entreprise')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='vehiculeApp.vehicule')),
            ],
        ),
    ]
