# Generated by Django 5.2.17 on 2026-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='user_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
