# Generated by Django 5.2.17 on 2026-10-06 14:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0003_alter_entreprise_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('type_vehicule', models.CharField(choices=[('c', 'Camion'), ('f', 'Fourgon'), ('s', 'Semi-remorque'), ('r', 'Remorque')], max_length=50)),
                ('capacite_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La capacité doit être supérieure à 0 kg.')])),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
